services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stok_hp_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - mysql_db
      - www_app-network
    ports:
      - "8092:80"

networks:
  mysql_db:
    driver: bridge
  www_app-network:
    driver: bridge
