services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stok_hp_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - mysql_db
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    container_name: stok_hp_nginx
    restart: unless-stopped
    ports:
      - "8092:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - mysql_db

networks:
  mysql_db:
    driver: bridge
